######################################################################
##
## Filename: alu.udo
## Created on: Sun Sep 23 16:48:50 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
