######################################################################
##
## Filename: control_unit.udo
## Created on: Sat Sep 22 22:02:31 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
