######################################################################
##
## Filename: tb_alu_control.udo
## Created on: Sat Sep 22 20:17:02 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
