######################################################################
##
## Filename: tb_adder.udo
## Created on: Tue Sep 25 22:36:39 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
