######################################################################
##
## Filename: tb_forwarding_unit.udo
## Created on: Sun Nov 11 16:25:46 Romance Standard Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
