######################################################################
##
## Filename: tb_pc_handle.udo
## Created on: Tue Sep 25 21:56:15 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
