######################################################################
##
## Filename: tb_reg_exmem.udo
## Created on: Sat Oct 20 20:04:47 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
