######################################################################
##
## Filename: tb_reg_ifid.udo
## Created on: Sat Oct 20 19:55:54 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
