######################################################################
##
## Filename: tb_sign_extend.udo
## Created on: Fri Sep 21 18:00:33 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
