######################################################################
##
## Filename: tb_shift_two.udo
## Created on: Sat Sep 22 17:59:10 Romance Daylight Time 2012
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
