onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /tb_toplevel/clk
add wave -noupdate /tb_toplevel/reset
add wave -noupdate /tb_toplevel/command
add wave -noupdate /tb_toplevel/bus_address_in
add wave -noupdate /tb_toplevel/bus_data_in
add wave -noupdate /tb_toplevel/status
add wave -noupdate /tb_toplevel/bus_data_out
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/clk
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/reset
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/processor_enable
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/imem_address
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/imem_data_in
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/dmem_data_in
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/dmem_address
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/dmem_address_wr
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/dmem_data_out
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/dmem_write_enable
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/current_state
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/next_state
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/reg_dst
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_src
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/mem_to_reg
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/reg_write
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/mem_read
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/mem_write
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/branch
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_op
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/jump
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_x
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_y
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_in
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/alu_out
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/flags
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/pc_current
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/offset
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/pc_next
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/rs
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/rt
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/rd_addr
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/data_to_write
add wave -noupdate /tb_toplevel/uut/mips_sc_processor/exec_state
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {0 ps} 0}
configure wave -namecolwidth 150
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {999050 ps} {1000050 ps}
